### ISSUE TITLE
Connection gets stuck

### ISSUE THREAD

**Issue by ghostzero** [fdgt-apis/api#125]
**Describe the bug**
I would like to add fdgt to my [ghostzero/tmi](https://github.com/ghostzero/tmi) client. Unfortunately replacing the domains from irc.chat.twitch.tv to irc.fdgt.dev does not work as expected.

**To Reproduce**
1. Checkout `ghostzero/tmi:v2-develop`
2. Run the `FdgtTest` test
4. Connection gets stuck

**Expected behavior**
The test is OK (1 test, 1 assertion). The connection is established without problems.

**Desktop**
 - OS: Windows 10, Version 1909 (OS Build 18363.657)
 - PHP: 7.4.3 (cli) (built: Feb 18 2020 17:29:46) ( ZTS Visual C++ 2017 x64 )

**Additional context**

**Comment by trezy** [comment]
The good news is that I can tell you exactly what the issue is: Our TCP port is currently busted.

The bad news: I can't give you an ETA an the fix. I was working on it, but I'm currently down with a pretty wicked illness. I'm hoping to get back on my feet and have it figured out next week, but I'm not making any promises.

I'll let you know here when the TCP port is restored so you can give it another shot.

**Comment by ghostzero** [comment]
Any updates?

**Comment by trezy** [comment]
Yup, the API should be working on all ports and protocols:
| Protocol | Port |
|-|-|
| `HTTP` | `80` |
| `HTTPS` | `443` |
| `TCP` | `6667` |
| `TCP` w/ `TLS` | `6697` |

**Comment by ghostzero** [comment]
Still having connection issues.
